### PR TITLE
Migration allow null for created and modified

### PR DESCRIPTION
**Pull request by LubosRemplik**
Was not able to use your Seed without this

### CODE REVIEW

**Comment by ishanvyas22** [comment]
What error are you facing?

**Comment by LubosRemplik** [comment]
image

**Comment by ishanvyas22** [comment]
It's related to your MySQL settings. You have to set `sql_mode` to blank in order to fix this issue.

**Comment by LubosRemplik** [comment]
IMO better to get it work in mysql default `sql_mode` which is set in my case, the migration i have created allows create and modified to be null so it works with default mode :)

**Comment by ishanvyas22** [comment]
Yeah that is also valid point. I'll merge it then.

**Comment by ishanvyas22** [comment]
Thanks!

**Pull request merged**
